Repository TeamBookTez/booktez-client, pull requests merged in 2022-02, with the labels that each got.

#201 Refactor web standards
  package.json
  public/index.html
  src/components/addBook/AddBookDefault.tsx
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/ShowModal.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/MainHeader.tsx
  src/components/common/NavHeader.tsx
  src/components/common/PopUpDelete.tsx
  src/components/detail/DetailArticleWrapper.tsx
  src/components/detail/DetailArticleWrapperLabeling.tsx
  src/components/detail/ExamplePeriNote.tsx
  src/components/detail/ExamplePreNote.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/components/landing/LandingCard.tsx
  src/components/landing/LandingFive.tsx
  src/components/landing/LandingFour.tsx
  src/components/landing/LandingOne.tsx
  src/components/landing/LandingThree.tsx
  src/components/login/LoginForm.tsx
  src/components/main/RecentBooks.tsx
  src/components/myPage/BottomContent.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/BookNote.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/pages/DetailExample.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/ToBe.tsx
  src/utils/lib/api.ts
Labels: :hammer_and_wrench: fix, :construction: refactor, 🐶주함

#203 Feature bookcase divide api
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/common/MainHeader.tsx
  src/pages/Bookcase.tsx
  src/utils/lib/api.ts
  src/utils/lib/index.ts
Labels: :hammer_and_wrench: fix, :construction: refactor, 🐢상언

#204 Fix addbook and complete
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/ShowModal.tsx
  src/components/bookcase/cardSection/BookCard.tsx
Labels: :tada: feature, :construction: refactor, 🦅규민

#206 Feature nav shadow 구현
  package.json
  src/components/addBook/AddBookDefault.tsx
  src/components/addBook/BookEmpty.tsx
  src/components/addBook/SearchBar.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/Navigation.tsx
  src/components/common/CommonLayout.tsx
  src/components/common/MainLayout.tsx
  src/components/common/NavWrapper.tsx
  yarn.lock
Labels: :hammer_and_wrench: fix, :tada: feature, :construction: refactor, 🐶주함

#211 Fix book note drawer ani
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/Navigator.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, :construction: refactor, 🐶주함

#213 feat: create bookcase get custom hook
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/pages/Bookcase.tsx
  src/utils/lib/api.ts
  src/utils/lib/index.ts
Labels: :construction: refactor, 🐢상언

#207 Feature book note refactor && Reactor bookcase
  .gitignore
  .vscode/settings.json
  package.json
  src/assets/icons/periQuestionIcon.svg
  src/assets/images/index.ts
  src/components/Router.tsx
  src/components/addBook/SearchBar.tsx
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/index.ts
  src/components/bookNote/periNote/Complete.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/periNote/PeriNoteInput.tsx
  src/components/bookNote/periNote/PriorAnswer.tsx
  src/components/bookNote/periNote/PriorQuestion.tsx
  src/components/bookNote/preNote/InputQuestion.tsx
  src/components/bookNote/preNote/PopUpPreDone.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookNote/preNote/QuestionThree.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/Navigation.tsx
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/bookcase/index.ts
  src/components/common/PopUpDelete.tsx
  src/components/common/PopUpExit.tsx
  src/components/common/styled/LabelQuestion4Depth.tsx
  src/components/common/styled/PopUp.tsx
  src/components/detail/ExamplePeriNote.tsx
  src/components/detail/ExamplePeriQuestion.tsx
  src/components/detail/index.ts
  src/components/main/RecentBooks.tsx
  src/components/signup/LastStep.tsx
  src/pages/BookNote.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/styles/globalStyle.ts
  src/utils/dataType.ts
  src/utils/lib/api.ts
  src/utils/lib/bookNote.ts
  src/utils/mockData.ts
  src/utils/tree.ts
  yarn.lock
Labels: :question: bug, 🐜소령, :tada: feature, :construction: refactor

#215 Feature global state recoil
  package.json
  src/App.tsx
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/SearchBar.tsx
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookcase/Navigation.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/Loading.tsx
  src/components/common/MainHeader.tsx
  src/components/common/MainLayout.tsx
  src/components/common/NavWrapper.tsx
  src/components/common/PopUpDelete.tsx
  src/components/detail/ExamplePreNote.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/components/main/RecentBooks.tsx
  src/components/myPage/TopContent.tsx
  src/components/signup/LastStep.tsx
  src/pages/AddBook.tsx
  src/pages/BookNote.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/pages/DetailExample.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/utils/atoms.ts
  src/utils/dataType.ts
  src/utils/lib/api.ts
  src/utils/lib/bookNote.ts
  src/utils/useHooks.ts
  yarn.lock
Labels: :question: bug, :hammer_and_wrench: fix, :construction: refactor, 🐶주함

#221 Hotfix add book
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookcase/Cards.tsx
  src/components/detail/ExamplePreNote.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/components/login/LoginForm.tsx
  src/components/main/RecentBooks.tsx
  src/components/myPage/TopContent.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/ThirdStep.tsx
Labels: :hammer_and_wrench: fix, 🐜소령

#222 Hotfix bookcase swr
  src/components/addBook/ShowModal.tsx
  src/components/main/RecentBooks.tsx
  src/components/myPage/TopContent.tsx
  src/utils/lib/api.ts
Labels: :hammer_and_wrench: fix, 🐜소령

#223 Hotfix bookcase swr
  src/utils/useHooks.ts
Labels: :hammer_and_wrench: fix, 🐜소령

#224 Feature fractoring is login with recoil
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/periNote/Complete.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/detail/ExamplePreNote.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/components/main/RecentBooks.tsx
  src/components/myPage/BottomContent.tsx
  src/components/myPage/TopBanner.tsx
  src/components/myPage/TopContent.tsx
  src/pages/BookNote.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/pages/DetailExample.tsx
  src/pages/MyPage.tsx
  src/utils/lib/api.ts
  src/utils/useHooks.ts
Labels: :construction: refactor, 🐶주함

#226 stepup modal UI 수정 && QA 반영
  src/components/bookNote/periNote/Complete.tsx
  src/components/bookNote/stepUp/ThreeCaseModal.tsx
  src/components/bookcase/Navigation.tsx
  src/components/common/NavWrapper.tsx
Labels: :hammer_and_wrench: fix, :construction: refactor, 🐢상언
