Repository TeamBookTez/booktez-client, pull requests merged in 2022-01, with the labels that each got.

#3 fix: index page에서 main으로 리다이렉트될 수 있도록 추가
  src/components/Router.tsx
Labels: :hammer_and_wrench: fix, 소령, 주함

#11 feat: 회원가입페이지 HTML 설계
  src/pages/SignUp.tsx
Labels: :tada: feature, 규민

#12 feat: 로그인 페이지 html 구성
  src/pages/Login.tsx
Labels: :tada: feature, 주함

#8 :tada: feat: 메인 페이지 구조 설계
  src/components/Router.tsx
  src/components/bookcase/BookcaseWrapper.tsx
  src/components/bookcase/Navigation.tsx
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/bookcase/index.ts
  src/components/common/Button.tsx
  src/components/common/MainHeader.tsx
  src/components/common/NavHeader.tsx
  src/components/common/NavWrapper.tsx
  src/components/common/index.ts
  src/components/main/Banner.tsx
  src/components/main/MainWrapper.tsx
  src/components/main/index.ts
  src/index.tsx
  src/pages/Bookcase.tsx
  src/pages/Main.tsx
  src/pages/SignUp.tsx
  src/pages/index.ts
  src/styles/globalStyle.ts
  tsconfig.json
Labels: 소령, :tada: feature

#24 Feature login animation + svg id 추가
  .vscode/settings.json
  src/assets/icons/alertIcon.svg
  src/assets/icons/coolIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/logoIcon.svg
  src/assets/icons/sightIcon.svg
  src/components/login/LoginForm.tsx
  src/components/login/LoginNavSection.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 주함

#26 Feature add book structure
  src/assets/asset.d.ts
  src/assets/icons/bookcaseIcon.svg
  src/assets/icons/cancelIcon.svg
  src/assets/icons/homeIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/myPageIcon.svg
  src/assets/icons/searchIcon.svg
  src/assets/icons/toBeIcon.svg
  src/assets/images/index.ts
  src/components/Router.tsx
  src/components/addBook/AddBookWrapper.tsx
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/BookList.tsx
  src/components/addBook/SearchBar.tsx
  src/components/common/MainHeader.tsx
  src/components/common/MainLayout.tsx
  src/components/common/index.ts
  src/components/main/MainWrapper.tsx
  src/pages/AddBook.tsx
  src/pages/index.ts
Labels: :tada: feature, 규민

#30 Feature common navwrapper
  src/assets/icons/bookcaseIcon.svg
  src/assets/icons/homeIcon.svg
  src/assets/icons/myPageIcon.svg
  src/assets/icons/toBeIcon.svg
  src/components/common/NavHeader.tsx
  src/components/common/NavWrapper.tsx
  src/components/login/LoginNavSection.tsx
  src/pages/Signup.tsx
Labels: 소령, :tada: feature

#34 Feature addbook styling
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/BookList.tsx
  src/components/addBook/SearchBar.tsx
Labels: :tada: feature, 🦅규민

#36 Feature signup component passing
  src/assets/icons/alertIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/noSightIcon.svg
  src/assets/icons/sightIcon.svg
  src/components/Router.tsx
  src/components/common/MainLayout.tsx
  src/components/login/LoginForm.tsx
  src/components/login/LoginNavSection.tsx
  src/components/login/index.ts
  src/components/signup/FirstStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: :tada: feature, :construction: refactor, 🐶주함

#29 feat: 마이페이지 뷰 퍼블리싱
  src/assets/icons/editProfileIcon.svg
  src/assets/icons/index.ts
  src/assets/images/index.ts
  src/assets/images/userImage.png
  src/components/Router.tsx
  src/components/bookcase/cardSection/AddBookCard.tsx
  src/components/common/Button.tsx
  src/components/mypage/BottomContent.tsx
  src/components/mypage/MyPageWrapper.tsx
  src/components/mypage/TopBanner.tsx
  src/components/mypage/TopContent.tsx
  src/components/mypage/index.ts
  src/pages/MyPage.tsx
  src/pages/index.ts
Labels: :tada: feature, 🐢상언

#39 Feature addbook styling
  .gitignore
  src/components/addBook/AddBookWrapper.tsx
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/BookList.tsx
  src/components/addBook/SearchBar.tsx
  src/utils/api.ts
Labels: :tada: feature, 🦅규민

#41 feat: 회원가입 뷰 애니메이션 완료
  src/components/login/LoginNavSection.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Signup.tsx
Labels: :tada: feature, 🐶주함

#45 refactor: 버튼 컴포넌트화 및 디자인 수정 적용
  src/components/bookcase/NoCards.tsx
  src/components/bookcase/cardSection/AddBookCard.tsx
  src/components/common/MainHeader.tsx
  src/components/common/MainLayout.tsx
  src/components/login/LoginForm.tsx
  src/components/login/LoginNavSection.tsx
  src/components/main/Banner.tsx
  src/components/mypage/TopContent.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
Labels: :construction: refactor, 🐢상언

#49 Feature input function
  .eslintrc.json
  .vscode/settings.json
  src/assets/icons/cancelIcon.svg
  src/assets/icons/searchIcon.svg
  src/assets/images/index.ts
  src/assets/images/signupFirstImage.png
  src/assets/images/signupSecondImage.png
  src/assets/images/signupThirdImage.png
  src/components/Router.tsx
  src/components/addBook/BookList.tsx
  src/components/addBook/SearchBar.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/NoCards.tsx
  src/components/bookcase/cardSection/AddBookCard.tsx
  src/components/bookcase/index.ts
  src/components/common/AlertLabel.tsx
  src/components/common/MainHeader.tsx
  src/components/common/MainLayout.tsx
  src/components/common/NavHeader.tsx
  src/components/common/NavWrapper.tsx
  src/components/common/index.ts
  src/components/common/styled/Button.tsx
  src/components/common/styled/Input.tsx
  src/components/common/styled/LabelHidden.tsx
  src/components/login/LoginForm.tsx
  src/components/main/Banner.tsx
  src/components/mypage/MyPageWrapper.tsx
  src/components/mypage/index.ts
  src/components/signup/FirstStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/SignupLayout.tsx
  src/components/signup/ThirdStep.tsx
  src/components/signup/index.ts
  src/pages/AddBook.tsx
  src/pages/MyPage.tsx
  src/pages/Signup.tsx
  src/styles/globalStyle.ts
  src/styles/styled.d.ts
Labels: :tada: feature, :construction: refactor, 🐶주함

#53 Feature theme setting
  .eslintrc.json
  public/fonts/Pretendard-Bold.ttf
  public/fonts/Pretendard-ExtraBold.ttf
  public/fonts/Pretendard-Medium.ttf
  public/fonts/Pretendard-Regular.ttf
  public/fonts/Pretendard-SemiBold.ttf
  public/index.html
  src/components/addBook/SearchBar.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/MainHeader.tsx
  src/components/common/NavWrapper.tsx
  src/components/main/Banner.tsx
  src/components/mypage/BottomContent.tsx
  src/components/mypage/TopBanner.tsx
  src/components/mypage/TopContent.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Signup.tsx
  src/styles/globalStyle.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 🐜소령, :tada: feature

#59 design: 마이페이지 폰트 적용 + 레이아웃 변경
  src/components/mypage/BottomContent.tsx
  src/components/mypage/TopBanner.tsx
  src/components/mypage/TopContent.tsx
  src/styles/theme.ts
Labels: :construction: refactor, 🐢상언

#60 Feature input function
  package.json
  src/assets/icons/searchIcon.svg
  src/components/addBook/SearchBar.tsx
  src/components/common/InputEmail.tsx
  src/components/common/InputPwd.tsx
  src/components/common/index.ts
  src/components/common/styled/Button.tsx
  src/components/login/LoginForm.tsx
  src/components/login/LoginNavSection.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  yarn.lock
Labels: :question: bug, :tada: feature, :construction: refactor, 🐶주함

#63 Test swr setting
  .vscode/settings.json
  package.json
  src/components/Router.tsx
  src/components/addBook/SearchBar.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/main/Banner.tsx
  src/components/main/Recent.tsx
  src/components/main/index.ts
  src/pages/AddBook.tsx
  src/pages/Main.tsx
  src/pages/Test.tsx
  src/pages/index.ts
  src/utils/api.ts
  src/utils/lib/api.ts
  src/utils/lib/index.ts
  yarn.lock
Labels: 🐜소령, :tada: feature

#64 Feature debounce
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/SearchBar.tsx
  src/pages/AddBook.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🐶주함

#65 Feature signup api
  .gitignore
  src/components/signup/FirstStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Signup.tsx
  src/utils/auth.api.ts
  src/utils/check.ts
Labels: :tada: feature, 🐢상언

#68 Feature to be publishing
  src/assets/images/deviceImage.png
  src/assets/images/index.ts
  src/components/Router.tsx
  src/components/common/styled/Button.tsx
  src/pages/ToBe.tsx
  src/styles/theme.ts
Labels: :tada: feature, 🐶주함

#69 Test swr setting
  src/components/common/MainHeader.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/AddBook.tsx
  src/pages/Test.tsx
  src/utils/auth.api.ts
  src/utils/dataType.ts
  src/utils/lib/api.ts
  src/utils/lib/index.ts
Labels: :question: bug, 🐜소령, :construction: refactor

#70 마이페이지 디테일 변경 및 읽은 책 수에 따른 분기처리 뷰 구현
  package.json
  src/components/mypage/BookComment.tsx
  src/components/mypage/BottomContent.tsx
  src/components/mypage/TopBanner.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  yarn.lock
Labels: :tada: feature, :construction: refactor, 🐢상언

#71 로컬 회원가입 기능 보완 및 오류 수정
  src/components/common/InputEmail.tsx
  src/components/common/InputPwd.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/utils/auth.api.ts
Labels: :tada: feature, :construction: refactor, 🐢상언

#76 Feature my page info api
  src/components/addBook/ModalWrapper.tsx
  src/components/mypage/BottomContent.tsx
  src/components/mypage/TopBanner.tsx
  src/components/mypage/TopContent.tsx
  src/pages/Bookcase.tsx
  src/pages/MyPage.tsx
Labels: :tada: feature, 🦅규민

#77 Feature login api
  src/components/login/LoginForm.tsx
  src/pages/ToBe.tsx
Labels: :tada: feature, :construction: refactor, 🐶주함

#78 Feature main bottom
  src/assets/images/index.ts
  src/assets/images/mainDefault.png
  src/components/login/LoginForm.tsx
  src/components/main/Default.tsx
  src/components/main/Recent.tsx
  src/components/main/index.ts
  src/components/mypage/BottomContent.tsx
  src/components/mypage/TopBanner.tsx
  src/components/mypage/TopContent.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Bookcase.tsx
  src/pages/MyPage.tsx
  src/pages/Test.tsx
  src/utils/auth.api.ts
  src/utils/dataType.ts
  src/utils/lib/api.ts
  src/utils/lib/index.ts
Labels: 🐜소령, :tada: feature

#79 refactor login-signup
  src/components/common/InputEmail.tsx
  src/components/common/InputPwd.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Signup.tsx
  src/styles/styled.d.ts
  src/utils/check.ts
Labels: :construction: refactor, 🐶주함

#81 Feature book note section form
  src/assets/icons/checkIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/rightArrowIcon.svg
  src/components/bookNote/ExButton.tsx
  src/components/bookNote/PreNoteLayout.tsx
  src/components/bookNote/QuestionThree.tsx
  src/components/bookNote/StepUp.tsx
  src/components/bookNote/index.ts
Labels: 🐜소령, :tada: feature

#85 Feature hover delete
  src/assets/icons/deleteIcon.svg
  src/assets/icons/index.ts
  src/components/bookcase/Cards.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/main/Recent.tsx
Labels: :tada: feature, 🐶주함

#87 Feature booknote drawer
  src/assets/icons/booksIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/leftArrowIcon.svg
  src/components/Router.tsx
  src/components/bookNote/Drawer1.tsx
  src/components/bookNote/Drawer2.tsx
  src/components/bookNote/Drawer3.tsx
  src/components/bookNote/DrawerWrapper.tsx
Labels: :tada: feature, 🦅규민

#88 etc: (로그인/회원가입) 미사용 코드 제거
  src/components/login/LoginForm.tsx
  src/components/signup/ThirdStep.tsx
Labels: :construction: refactor, 🐶주함

#89 Feature booknote publishing
  src/assets/icons/index.ts
  src/assets/icons/saveIcon.svg
  src/components/Router.tsx
  src/components/addBook/ModalWrapper.tsx
  src/components/addBook/ShowModal.tsx
  src/components/booknote/Navigater.tsx
  src/components/booknote/PeriNote.tsx
  src/components/booknote/PreNote.tsx
  src/pages/BookNote.tsx
  src/pages/Signup.tsx
Labels: :tada: feature, 🐢상언

#90 Feature bookcase book api
  src/components/bookcase/Cards.tsx
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/main/Recent.tsx
  src/pages/Bookcase.tsx
Labels: :tada: feature, 🦅규민

#95 Feature book note q3
  src/assets/icons/binIcon.svg
  src/assets/icons/deleteIcon.svg
  src/assets/icons/index.ts
  src/components/Router.tsx
  src/components/bookNote/InputQuestion.tsx
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/PreNoteForm.tsx
  src/components/bookNote/QuestionThree.tsx
  src/components/bookNote/index.ts
  src/components/bookcase/cardSection/BookCard.tsx
  src/pages/BookNote.tsx
Labels: 🐜소령, :tada: feature

#99 Feature signup api
  src/components/Router.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Test.tsx
  src/utils/lib/index.ts
Labels: :construction: refactor, 🐢상언

#101 Feature peri note example
  src/components/Router.tsx
  src/components/bookNote/PeriNoteExample.tsx
  src/components/bookNote/index.ts
  src/components/booknote/PeriNote.tsx
  src/components/common/styled/LabelQuestion.tsx
  src/pages/MyPage.tsx
  src/pages/Test.tsx
Labels: :tada: feature, 🐶주함

#105 Feature book note pre
  .vscode/settings.json
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/ExButton.tsx
  src/components/bookNote/StepUp.tsx
  src/components/bookNote/common/Drawer1.tsx
  src/components/bookNote/common/Drawer2.tsx
  src/components/bookNote/common/Drawer3.tsx
  src/components/bookNote/common/DrawerWrapper.tsx
  src/components/bookNote/index.ts
  src/components/bookNote/preNote/DrawerPre.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookNote/preNote/PreNoteForm.tsx
  src/components/bookNote/preNote/QuestionThree.tsx
  src/pages/BookNote.tsx
  src/styles/globalStyle.ts
Labels: :question: bug, 🐜소령, :tada: feature, :construction: refactor

#106 삭제 및 나가기 확인 팝업 구현
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/PopUpDelete.tsx
  src/components/common/PopUpExit.tsx
  src/components/common/index.ts
  src/components/common/styled/PopUp.tsx
  src/pages/Bookcase.tsx
  src/pages/ToBe.tsx
Labels: :tada: feature, 🐶주함

#113 Feature book note pre
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/Navigator.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/pages/BookNote.tsx
  src/pages/Test.tsx
Labels: :question: bug, 🐜소령, :tada: feature

#111 Feature perinote
  src/assets/icons/guideIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/moreIcon.svg
  src/components/Router.tsx
  src/components/bookNote/periNote/AnswerInput.tsx
  src/components/bookNote/periNote/PairsWrapper.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/periNote/QuestionInput.tsx
  src/pages/Bookcase.tsx
  src/pages/MyPage.tsx
Labels: :tada: feature, 🦅규민

#112 Feature booknote stepup publishing
  src/components/bookNote/StepUp.tsx
  src/components/bookNote/preNote/PreNoteForm.tsx
  src/components/bookNote/stepUp/CarouselDots.tsx
  src/components/bookNote/stepUp/OneCaseModal.tsx
  src/components/bookNote/stepUp/PeriModal.tsx
  src/components/bookNote/stepUp/ThreeCaseModal.tsx
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/utils/dataCarousel.ts
Labels: :tada: feature, 🐢상언

#117 fix: navigation color 재정의 according to router url 변경
  src/components/common/NavWrapper.tsx
Labels: :hammer_and_wrench: fix, 🐜소령

#119 Feature book note pre api
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookNote/preNote/QuestionThree.tsx
  src/pages/BookNote.tsx
  src/utils/lib/index.ts
Labels: 🐜소령, :tada: feature

#124 Feature bookcase if empty
  src/assets/images/emptyBookImage.png
  src/assets/images/index.ts
  src/components/bookcase/Cards.tsx
  src/components/bookcase/cardSection/AddBookCard.tsx
  src/components/bookcase/cardSection/Empty.tsx
  src/pages/Bookcase.tsx
Labels: :tada: feature, 🦅규민

#128 Feature book note pre api
  .vscode/settings.json
  src/components/bookNote/preNote/InputQuestion.tsx
  src/components/bookNote/preNote/PopUpPreDone.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookNote/preNote/QuestionThree.tsx
  src/components/common/PopUpExit.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, 🐜소령, :tada: feature

#129 Feature 4depth
  src/assets/icons/index.ts
  src/assets/icons/toggleIcon.svg
  src/components/Router.tsx
  src/components/bookNote/stepUp/CarouselDots.tsx
  src/components/bookNote/stepUp/OneCaseModal.tsx
  src/components/bookNote/stepUp/PeriModal.tsx
  src/components/bookNote/stepUp/ThreeCaseModal.tsx
  src/components/common/styled/NoteModalWrapper.tsx
  src/components/detail/ExamplePeriNote.tsx
  src/components/detail/ExamplePreNote.tsx
  src/pages/DetailBookNote.tsx
  src/pages/DetailExample.tsx
  src/utils/dataCarousel.ts
  src/utils/mockData.ts
Labels: :tada: feature, 🐶주함

#130 Feature mypage img bug
  src/components/mypage/TopBanner.tsx
  src/pages/MyPage.tsx
Labels: :question: bug, 🦅규민

#132 Feature bookcase add api
  src/components/addBook/ShowModal.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/bookcase/cardSection/Empty.tsx
  src/components/login/LoginForm.tsx
  src/components/main/Default.tsx
  src/components/main/Recent.tsx
  src/components/main/index.ts
  src/pages/Bookcase.tsx
Labels: :tada: feature, :construction: refactor, 🐢상언

#134 Feature popupdelete
  src/components/bookcase/Cards.tsx
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/PopUpDelete.tsx
  src/components/main/Recent.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/utils/lib/api.ts
  src/utils/lib/index.ts
Labels: :question: bug, 🦅규민

#137 Feature 4depth
  src/components/bookNote/stepUp/ThreeCaseModal.tsx
  src/components/detail/DetailArticleWrapperLabeling.tsx
  src/components/detail/ExamplePeriNote.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/components/detail/StepUpOnExample.tsx
  src/components/detail/index.ts
  src/components/main/Banner.tsx
  src/pages/BookNote.tsx
  src/pages/DetailExample.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/utils/mockData.ts
Labels: :tada: feature, 🐶주함

#138 Feature book note peri patch
  src/assets/icons/answerLabelIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/moreIcon.svg
  src/assets/icons/periAnswerIcon.svg
  src/assets/icons/periQuestionIcon.svg
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/periNote/AnswerInput.tsx
  src/components/bookNote/periNote/PairsWrapper.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/periNote/QuestionInput.tsx
  src/pages/BookNote.tsx
  src/utils/dataType.ts
Labels: 🐜소령, :tada: feature

#139 Feature main display books - 주함이 검토 부탁합니다
  src/components/common/PopUpDelete.tsx
  src/components/main/Recent.tsx
Labels: :question: bug, :tada: feature, 🦅규민

#140 Feature islogin seok
  src/components/common/MainHeader.tsx
  src/components/main/Banner.tsx
Labels: :tada: feature, 🐢상언

#141 Feature islogin kyum
  src/components/myPage/TopContent.tsx
Labels: :tada: feature, 🦅규민

#148 Feature stepup button
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/PeriNoteExample.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookNote/preNote/PreNoteForm.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/detail/DetailArticleWrapperLabeling.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/pages/BookNote.tsx
  src/pages/DetailExample.tsx
Labels: :hammer_and_wrench: fix, 🐜소령, :tada: feature

#149 Feature addbook modify
  src/components/addBook/AddBookDefault.tsx
  src/components/addBook/BookEmpty.tsx
  src/components/addBook/BookList.tsx
  src/components/addBook/ShowModal.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/main/Recent.tsx
  src/pages/AddBook.tsx
  src/pages/BookNote.tsx
  src/pages/Bookcase.tsx
  src/pages/Main.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🦅규민

#151 Feature randing client api
  src/components/Router.tsx
  src/utils/lib/api.ts
Labels: :question: bug, :tada: feature, 🐶주함

#154 Feature check api joam
  src/components/Router.tsx
  src/components/addBook/BookInfoWrapper.tsx
  src/components/addBook/ShowModal.tsx
  src/components/common/MainHeader.tsx
  src/components/main/Recent.tsx
  src/components/myPage/TopBanner.tsx
  src/components/myPage/TopContent.tsx
  src/pages/MyPage.tsx
  src/pages/Test.tsx
  src/pages/index.ts
Labels: :tada: feature, 🐶주함

#156 Feature fix seok
  src/assets/images/index.ts
  src/assets/images/loginImage.png
  src/assets/images/mypageBannerImage.png
  src/assets/images/mypageReadImage.png
  src/assets/images/userImage.png
  src/components/login/LoginNavSection.tsx
  src/components/main/Banner.tsx
  src/components/main/Recent.tsx
  src/components/myPage/BottomContent.tsx
  src/components/myPage/TopBanner.tsx
  src/components/myPage/TopContent.tsx
  src/pages/Login.tsx
  src/pages/ToBe.tsx
Labels: :construction: refactor, 🐢상언

#157 Feature book note drawer
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/myPage/TopContent.tsx
  src/pages/BookNote.tsx
  src/pages/MyPage.tsx
Labels: :hammer_and_wrench: fix, 🐜소령

#158 Feature book api joam
  src/components/addBook/SearchBar.tsx
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/PeriNoteExample.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/common/PopUpDelete.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🐶주함

#159 Feature fix seok
  src/assets/images/deleteImage.png
  src/assets/images/index.ts
  src/assets/images/preBookImage.png
  src/components/bookNote/preNote/PopUpPreDone.tsx
  src/components/common/PopUpDelete.tsx
  src/components/common/styled/PopUp.tsx
Labels: :construction: refactor, 🐢상언

#160 Feature svg add
  src/assets/images/landingImage01.png
  src/assets/images/landingImage02.png
  src/components/landing/LandingCard.tsx
  src/components/landing/LandingFive.tsx
  src/components/landing/LandingFooter.tsx
  src/components/landing/LandingFour.tsx
  src/components/landing/LandingThree.tsx
  src/components/landing/LandingTwo.tsx
Labels: :construction: refactor, 🦅규민

#161 Feature book note bug
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/index.ts
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookcase/Navigation.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/pages/BookNote.tsx
  src/pages/DetailBookNote.tsx
Labels: :hammer_and_wrench: fix, 🐜소령, :tada: feature

#162 Feature joam
  src/assets/images/index.ts
  src/assets/images/logoGif.gif
  src/components/addBook/ShowModal.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/Loading.tsx
  src/components/main/Recent.tsx
  src/components/myPage/TopContent.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/pages/DetailExample.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🐶주함

#163 토스트인지 햄버거인지 샌드위치인지 구현해봄
  src/assets/icons/checkSaveIcon.svg
  src/assets/icons/index.ts
  src/components/bookNote/Navigator.tsx
  src/pages/BookNote.tsx
  src/styles/theme.ts
Labels: :tada: feature, 🐢상언

#146 Fix delete books 리팩토링
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookcase/Navigation.tsx
  src/components/bookcase/PeriRead.tsx
  src/components/common/MainLayout.tsx
  src/components/common/PopUpDelete.tsx
  src/components/main/RecentBooks.tsx
  src/components/main/index.ts
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/pages/Main.tsx
  src/styles/globalStyle.ts
Labels: :question: bug, :hammer_and_wrench: fix, :construction: refactor, 🐶주함

#165 Feature fix seok
  src/assets/icons/toBeIcon.svg
  src/assets/images/before1Image.png
  src/assets/images/before21Image.png
  src/assets/images/before22Image.png
  src/assets/images/before23Image.png
  src/assets/images/before3Image.png
  src/assets/images/deviceImage.png
  src/assets/images/drawerImage.png
  src/assets/images/exitImage.png
  src/assets/images/index.ts
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/stepUp/OneCaseModal.tsx
  src/components/bookNote/stepUp/ThreeCaseModal.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/NavWrapper.tsx
  src/components/common/PopUpDelete.tsx
  src/components/common/PopUpExit.tsx
  src/pages/BookNote.tsx
  src/pages/ToBe.tsx
  src/utils/mockData.ts
Labels: :question: bug, :construction: refactor, 🐢상언

#164 Feature book note bug
  src/assets/icons/toBeIcon.svg
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/index.ts
  src/components/bookNote/periNote/Complete.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/main/RecentBooks.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, 🐜소령, :tada: feature

#166 Feature fix seok
  src/assets/images/after11Image.png
  src/assets/images/after12Image.png
  src/assets/images/after13Image.png
  src/assets/images/index.ts
  src/components/bookNote/stepUp/PeriModal.tsx
  src/components/bookNote/stepUp/ThreeCaseModal.tsx
Labels: :tada: feature

#170 Feature fix seok
  public/index.html
Labels: :tada: feature, 🐢상언

#168 Feature landing page modify
  src/assets/images/landingBookNoteImage.png
  src/components/landing/LandingOne.tsx
  src/components/landing/LandingTwo.tsx
Labels: 🦅규민

#169 Feature booknote drawer img
  src/assets/icons/logoIcon.svg
  src/assets/images/drawerImageSmall.png
  src/assets/images/index.ts
  src/assets/images/preBookImage.png
  src/components/bookNote/DrawerWrapper.tsx
Labels: 🦅규민

#171 Feature qa joam
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/common/styled/LabelQuestion.tsx
  src/components/common/styled/LabelQuestion4Depth.tsx
  src/components/detail/ExamplePeriNote.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/BookNote.tsx
  src/pages/Login.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🐶주함

#172 Feature book note qa
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, 🐜소령, :construction: refactor

#175 Feature qaa joam
  src/components/bookcase/Navigation.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🐶주함

#177 Feature book note qa
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, 🐜소령, :construction: refactor

#178 Feature fix seok
  src/assets/images/exitImage.png
  src/assets/images/preBookImage.png
  src/components/addBook/BookInfoWrapper.tsx
  src/components/bookNote/preNote/PopUpPreDone.tsx
  src/components/common/PopUpExit.tsx
  src/components/myPage/BottomContent.tsx
  src/pages/BookNote.tsx
Labels: :construction: refactor, 🐢상언

#180 Feature fix seok
  src/assets/icons/detailIcon.svg
  src/assets/icons/index.ts
  src/assets/images/index.ts
  src/assets/images/signUpFinishImage.png
  src/components/detail/DetailArticleWrapper.tsx
  src/components/signup/LastStep.tsx
  src/pages/Signup.tsx
Labels: :construction: refactor, 🐢상언

#181 Feature 404 page
  src/assets/icons/404Icon.svg
  src/assets/icons/index.ts
  src/assets/icons/titleLogoIcon.svg
  src/assets/images/errorBackImage.png
  src/assets/images/index.ts
  src/components/common/Error404.tsx
  src/components/common/NavHeader.tsx
  src/components/common/NavWrapper.tsx
  src/components/login/LoginNavSection.tsx
Labels: 🐶주함

#183 Feature book note qa
  .vscode/settings.json
  src/components/bookNote/periNote/PeriNote.tsx
  src/pages/BookNote.tsx
  src/utils/lib/api.ts
Labels: :hammer_and_wrench: fix, 🐜소령

#182 fix: complete page navigate fromUrl 변경
  src/components/bookNote/periNote/Complete.tsx
  src/components/bookNote/preNote/PreNote.tsx
Labels: :construction: refactor, 🐢상언

#184 Feature book note qa
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/signup/LastStep.tsx
  src/pages/BookNote.tsx
Labels: 🐜소령, 🐶주함, 🐢상언, 🦅규민

#185 앱잼 종료 및 0차 릴리즈 얏호 >_<
  .vscode/settings.json
  README.md
  package.json
  src/App.tsx
  src/assets/icons/404Icon.svg
  src/assets/icons/detailIcon.svg
  src/assets/icons/index.ts
  src/assets/icons/titleLogoIcon.svg
  src/assets/images/errorBackImage.png
  src/assets/images/index.ts
  src/assets/images/signUpFinishImage.png
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/periNote/Complete.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookcase/Cards.tsx
  src/components/bookcase/PeriRead.tsx
  src/components/bookcase/PostRead.tsx
  src/components/bookcase/PreRead.tsx
  src/components/bookcase/Total.tsx
  src/components/common/Error404.tsx
  src/components/common/MainHeader.tsx
  src/components/common/NavHeader.tsx
  src/components/common/NavWrapper.tsx
  src/components/common/PopUpDelete.tsx
  src/components/detail/DetailArticleWrapper.tsx
  src/components/landing/LandingOne.tsx
  src/components/login/LoginForm.tsx
  src/components/login/LoginNavSection.tsx
  src/components/main/RecentBooks.tsx
  src/components/myPage/BottomContent.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/BookNote.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/pages/DetailExample.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/Signup.tsx
  src/states/index.ts
  src/utils/lib/api.ts
  yarn.lock
Labels: 🐜소령, :tada: feature, 🐶주함, 🐢상언, 🦅규민

#191 Feature book note qa
  src/components/bookNote/periNote/Complete.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookNote/preNote/QuestionThree.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, 🐜소령
