Repository TeamBookTez/booktez-client, pull requests merged in 2022-03, with the labels that each got.

#230 Feature landing mobile
  package.json
  src/assets/icons/index.ts
  src/assets/icons/landingMobileFour01.svg
  src/assets/icons/landingMobileFour02.svg
  src/assets/icons/landingMobileHeader.svg
  src/assets/icons/landingMobileIcon01.svg
  src/assets/icons/landingMobileIcon02.svg
  src/assets/icons/landingMobileIcon03.svg
  src/assets/icons/landingMobileMark.svg
  src/assets/icons/landingMobileThree.svg
  src/assets/images/index.ts
  src/assets/images/landingMobileBanner.png
  src/components/landing/LandingCard.tsx
  src/components/landing/LandingFour.tsx
  src/components/landing/LandingHeader.tsx
  src/components/landing/LandingOne.tsx
  src/components/landing/LandingThree.tsx
  src/components/landing/LandingTwo.tsx
  src/components/landing/MobileLandingCard.tsx
  src/components/landing/MobileLandingFive.tsx
  src/components/landing/MobileLandingFooter.tsx
  src/components/landing/MobileLandingFour.tsx
  src/components/landing/MobileLandingHeader.tsx
  src/components/landing/MobileLandingOne.tsx
  src/components/landing/MobileLandingThree.tsx
  src/components/landing/MobileLandingTwo.tsx
  src/pages/Landing.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/utils/useMediaQuery.tsx
  yarn.lock
Labels: :tada: feature, 🐢상언

#233 Hotfix book note patch
  package.json
  src/assets/icons/answerLabelIcon.svg
  src/assets/icons/index.ts
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/periNote/PeriNoteInput.tsx
  src/components/bookNote/periNote/PriorAnswer.tsx
  src/components/bookNote/periNote/PriorQuestion.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/pages/BookNote.tsx
  src/utils/useHooks.ts
  yarn.lock
Labels: :hammer_and_wrench: fix, 🐜소령, :tada: feature, :construction: refactor

#234 Feature qa joam
  src/components/addBook/BookInfoWrapper.tsx
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookNote/preNote/QuestionThree.tsx
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🐶주함

#235 Feature qa joamm
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/PopUpDelete.tsx
  src/components/landing/MobileLandingHeader.tsx
  src/components/landing/MobileLandingOne.tsx
  src/pages/DetailBookNote.tsx
Labels: :hammer_and_wrench: fix, 🐶주함

#236 fix: 엔터로 꼬리질문 추가 시 depth가 이상한 문제
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/periNote/PeriNoteInput.tsx
  src/components/bookNote/periNote/PriorAnswer.tsx
  src/components/bookNote/periNote/PriorQuestion.tsx
Labels: :question: bug, :hammer_and_wrench: fix, 🐜소령

#238 design: 북노트 작성 완료 QA 반영(닫기 버튼 삭제)
  src/components/bookNote/periNote/Complete.tsx
Labels: :hammer_and_wrench: fix

#239 Hotfix book note qa
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/Navigator.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/periNote/PriorAnswer.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/bookcase/cardSection/BookCard.tsx
  src/components/common/PopUpExit.tsx
  src/components/detail/ExamplePeriNote.tsx
  src/components/detail/ExamplePeriQuestion.tsx
  src/components/detail/ExamplePreNote.tsx
  src/components/main/RecentBooks.tsx
  src/pages/BookNote.tsx
  src/pages/Bookcase.tsx
  src/pages/DetailBookNote.tsx
  src/pages/Landing.tsx
  src/utils/atom.ts
  src/utils/useHooks.ts
Labels: :hammer_and_wrench: fix, 🐜소령, :tada: feature, :construction: refactor, 🐶주함

#240 feat: id, className 심기 for 데이터 추적
  src/components/addBook/ShowModal.tsx
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNote.tsx
  src/components/common/PopUpDelete.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/components/landing/LandingFooter.tsx
  src/components/landing/LandingOne.tsx
  src/components/login/LoginNavSection.tsx
  src/components/myPage/TopContent.tsx
  src/pages/BookNote.tsx
  src/pages/DetailBookNote.tsx
Labels: :tada: feature

#241 Hotfix book note qa
  src/assets/images/landingMobileBanner.png
  src/components/detail/ExamplePreNote.tsx
  src/components/landing/MobileLandingFooter.tsx
  src/components/landing/MobileLandingOne.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/utils/useMediaQuery.tsx
Labels: :hammer_and_wrench: fix, 🐜소령, 🐶주함

#242 Feature qa joammm
  src/components/signup/FirstStep.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Signup.tsx
Labels: :hammer_and_wrench: fix, :construction: refactor, 🐶주함

#243 Feature qa joammmm
  package.json
  src/pages/BookNote.tsx
  src/utils/atom.ts
  yarn.lock
Labels: :tada: feature, 🐶주함

#247 Feature fix kkm
  src/pages/BookNote.tsx
Labels: :hammer_and_wrench: fix, 🦅규민

#248 fix: 독서 전-중 질문 리스트 동기화 버그
  src/components/bookNote/preNote/PreNote.tsx
Labels: :question: bug, :hammer_and_wrench: fix, 🐜소령

#249 1차 릴리즈 버그 수정: 비밀번호 패턴 Regex 변경
  src/utils/check.ts
Labels: 🐜소령

#250 0321(월) PR 작업
  src/components/bookNote/DrawerWrapper.tsx
  src/components/bookNote/ExButton.tsx
  src/components/bookNote/StepUp.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/LastStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/Signup.tsx
Labels: :hammer_and_wrench: fix, :tada: feature, 🐶주함

#251 periNote reflow 버그 개선
  package.json
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/periNote/PeriNoteInput.tsx
  src/components/bookNote/periNote/PriorAnswer.tsx
  src/components/bookNote/periNote/PriorQuestion.tsx
  yarn.lock
Labels: :hammer_and_wrench: fix, 🐜소령, :tada: feature, :construction: refactor

#254 Release carousel refactor
  src/assets/images/index.ts
  src/assets/images/periNoteStepUp1Image.png
  src/assets/images/periNoteStepUp2Image.png
  src/assets/images/periNoteStepUp3Image.png
  src/assets/images/preNoteStepUp1Image.png
  src/assets/images/preNoteStepUp21Image.png
  src/assets/images/preNoteStepUp22Image.png
  src/assets/images/preNoteStepUp23Image.png
  src/assets/images/preNoteStepUp3Image.png
  src/components/bookNote/index.ts
  src/components/bookNote/periNote/PeriNote.tsx
  src/components/bookNote/preNote/PreNoteForm.tsx
  src/components/bookNote/stepUp/CarouselDots.tsx
  src/components/bookNote/stepUp/OneCaseModal.tsx
  src/components/bookNote/stepUp/PeriModal.tsx
  src/components/bookNote/stepUp/StepUpContentWrapper.tsx
  src/components/bookNote/stepUp/StepUpLayout.tsx
  src/components/bookNote/stepUp/ThreeCaseModal.tsx
  src/components/detail/ExamplePreNoteLabeling.tsx
  src/pages/DetailExample.tsx
  src/utils/exampleData.ts
Labels: 🐜소령, :construction: refactor
